-- ==========================================
-- MASTER ADMIN SETUP SCRIPT
-- ==========================================
-- This script ensures all tables (Products, Categories, Blogs) exist, 
-- have the correct columns, and are editable by the Admin Panel.
-- ==========================================

-- 1. PRODUCTS TABLE
-- =================
CREATE TABLE IF NOT EXISTS products (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    slug text not null unique,
    description text,
    price numeric,
    sale_price numeric,
    category_id bigint references categories(id),
    image_url text,
    gallery_images text[],
    in_stock boolean default true,
    is_active boolean default true,
    is_featured boolean default false,
    purity text,
    weight text,
    hallmark boolean default false,
    use_case text default 'All',
    specifications jsonb,
    care_instructions text[],
    highlights text[],
    note text,
    meta_description text,
    meta_keywords text
);

-- Enable full access for Admin Panel (Disable RLS)
ALTER TABLE products DISABLE ROW LEVEL SECURITY;

-- 2. CATEGORIES TABLE
-- =================
CREATE TABLE IF NOT EXISTS categories (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    slug text not null unique,
    description text,
    image text
);

-- Enable full access for Admin Panel (Disable RLS)
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;

-- 3. BLOG POSTS TABLE
-- =================
CREATE TABLE IF NOT EXISTS blog_posts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    slug text not null unique,
    excerpt text,
    content text,
    image text,
    author text default 'Admin',
    is_published boolean default true,
    published_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable full access for Admin Panel (Disable RLS)
ALTER TABLE blog_posts DISABLE ROW LEVEL SECURITY;

-- 4. ADMIN USERS TABLE
-- =================
CREATE TABLE IF NOT EXISTS admin_users (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    email text not null unique,
    password_hash text, -- In a real app, store hashed passwords. For this demo, we use code-based auth.
    name text,
    role text default 'admin',
    last_login timestamp with time zone
);

ALTER TABLE admin_users DISABLE ROW LEVEL SECURITY;

-- 5. TESTIMONIALS TABLE (Optional but good for full site control)
-- =================
CREATE TABLE IF NOT EXISTS testimonials (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    role text, -- e.g. "Customer"
    content text not null,
    image text,
    rating integer default 5,
    is_active boolean default true
);

ALTER TABLE testimonials DISABLE ROW LEVEL SECURITY;

-- 6. STORAGE BUCKETS
-- =================
-- Ensure buckets exist for all content types
INSERT INTO storage.buckets (id, name, public) VALUES ('product-images', 'product-images', true) ON CONFLICT (id) DO UPDATE SET public = true;
INSERT INTO storage.buckets (id, name, public) VALUES ('category-images', 'category-images', true) ON CONFLICT (id) DO UPDATE SET public = true;
INSERT INTO storage.buckets (id, name, public) VALUES ('blog-images', 'blog-images', true) ON CONFLICT (id) DO UPDATE SET public = true;
INSERT INTO storage.buckets (id, name, public) VALUES ('general-images', 'general-images', true) ON CONFLICT (id) DO UPDATE SET public = true;

-- Allow Update/Delete/Insert for everyone (since we are bypassing Auth for this Admin Demo)
-- Note: In a strict production environment with Supabase Auth, you would use authenticated policies.
DROP POLICY IF EXISTS "Public Access Product Images" ON storage.objects;
CREATE POLICY "Public Access Product Images" ON storage.objects FOR ALL USING ( bucket_id = 'product-images' ) WITH CHECK ( bucket_id = 'product-images' );

DROP POLICY IF EXISTS "Public Access Category Images" ON storage.objects;
CREATE POLICY "Public Access Category Images" ON storage.objects FOR ALL USING ( bucket_id = 'category-images' ) WITH CHECK ( bucket_id = 'category-images' );

DROP POLICY IF EXISTS "Public Access Blog Images" ON storage.objects;
CREATE POLICY "Public Access Blog Images" ON storage.objects FOR ALL USING ( bucket_id = 'blog-images' ) WITH CHECK ( bucket_id = 'blog-images' );

DROP POLICY IF EXISTS "Public Access General Images" ON storage.objects;
CREATE POLICY "Public Access General Images" ON storage.objects FOR ALL USING ( bucket_id = 'general-images' ) WITH CHECK ( bucket_id = 'general-images' );
